### ISSUE TITLE
/libgps-master/examples + make fail

### ISSUE THREAD

**Issue by ssinfod** [wdalmut/libgps#3]
Hello, I am trying to build the example for the repository but it fails.

~/libgps-master/examples $ make
/usr/bin/gcc -g -Wall -O3 -o ../build/position_logger position_logger.c -lgps -lm
position_logger.c:3:17: fatal error: gps.h: No such file or directory
 #include <gps.h>
                 ^
compilation terminated.
Makefile:10: recipe for target 'position_logger' failed
make: **\* [position_logger] Error 1

**Comment by ssinfod** [comment]
I made some changed to the makefile from the example folder:

RM=/bin/rm
CC=/usr/bin/gcc
OUTPUT_PATH=../build
CFLAGS=-g -Wall -O3
MAKE=/usr/bin/make
INCLUDE = -I./../src
LIB_GPS = -L ../build -lgps

all:    position_logger gpslogger

position_logger:
    ${CC} ${CFLAGS} ${INCLUDE} -o ${OUTPUT_PATH}/position_logger position_logger.c ${LIB_GPS} -lm

Do you think that is a valid solution ?

**Comment by wdalmut** [comment]
i think so. :+1:
