### ISSUE TITLE
~/build/example/position_logger.c doesn't work

### ISSUE THREAD

**Issue by cayofontana** [wdalmut/libgps#4]
Hi wdalmut,

I have a UBLOX GPS NEO 6M device and i try get data using your libgps but without success.
When i compile and execute the position_logger.c example, the program do nothing. Only stays in loop on console.
Before use that, i install the gpsd software to test my device and see the data on console screen and it's work fine.

Can you helpe me?

Thank you!

**Comment by cayofontana** [comment]
After i compile and running the tests, this lib work fine.

Thank you!

**Comment by wdalmut** [comment]
ok
