### ISSUE TITLE
Cannot link the library in other dir.

### ISSUE THREAD

**Issue by benstealer** [wdalmut/libgps#7]
Hey all,

I've got a problem with linking the libgps.a in another Makefile. 
By trying to use the functions of gps.h i always get undefined references.

foo.cpp:(.text+0x1a4): undefined reference to 'gps_init()

I thought about compiling them again in the project folder. But I guess it isnt necessary?

My Makefile looks like:

LIBS = -lbcm2835
------Compiling all my .cpp files---------
--------and getting their .o files----------

foo: $(OBJECTS) 
                  $(CC) $^ $(LIBS) -lgps - o foo

clean:
          rm -rf *.o foo

Could someone help?

Would be awesome :)

**Comment by wdalmut** [comment]
Probably the include path for your gcc is not the default one. You have to pass -I options and other to locate the .h and .a file position

like -I /usr/lib/include

**Comment by benstealer** [comment]
hey I already tried to locate them there.
my solution was today copying the files into my project folder and compile them there.
it works fine now

thank you anyway
